// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/arrays_test.fbs
// root_type ArrayTable
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'arrays_test.MyGame.Example.ArrayStruct'/>
        <see cref = 'arrays_test.MyGame.Example.ArrayTable'/>
        <see cref = 'arrays_test.MyGame.Example.LargeArrayStruct'/>
        <see cref = 'arrays_test.MyGame.Example.NestedStruct'/>
    */
    public interface arrays_test {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below. Not because FlatBuffers stores scalars raw - AdHoc
        // lays out its own frame and may varint-encode anything - but because a .fbs carries no claim about
        // WHERE a field's values sit: it has no sint32-versus-fixed32 choice, no declared range, no units. The
        // physics of each number is therefore yours to state, and it is the single highest-value edit to make
        // to this file. Fields whose name or documentation does hint at an answer carry a `// physics:` line
        // naming the candidate and the reason; the choice is deliberately left open.
        //   [A(min)] floor, rare excursions up     [V(max)] hugs a ceiling
        //   [X(amplitude)] two-sided around zero   [MinMax(a, b)] hard range, bit-packed, no varint
        // Check the arithmetic first: varint pays while the typical distance from the base stays under about
        // two million, and always loses past 268 435 455 - so timestamps, scaled coordinates, monotonic ids
        // and hashes are losses at a zero base. A span under one byte is rejected; use [MinMax] there.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "ArrayTable";
            public const string file_identifier = "ARRT";
            public const string file_extension = "mon";
        }

        // namespace MyGame
        public struct MyGame {

            // namespace MyGame.Example
            public struct Example {

                /**
                FlatBuffers base type: byte
                */
                public enum TestEnum {
                    A = 0,
                    B = 1,
                    C = 2,
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class NestedStruct {
                    [D(2)] int[] a;
                    MyGame.Example.TestEnum b;
                    [D(2)] MyGame.Example.TestEnum[] c;
                    [D(2)] long[] d;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class ArrayStruct {
                    float a;
                    [D(15)] int[] b;
                    sbyte c;
                    [D(2)] MyGame.Example.NestedStruct[] d;
                    int e;
                    [D(2)] long[] f;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class LargeArrayStruct {
                    [D(64)] byte[] d;
                    [D(64)] float[] e;
                    [D(64)] bool[] f;
                    [D(64)] MyGame.Example.NestedStruct[] g;
                    [D(64)] MyGame.Example.TestEnum[] h;
                }

                public class ArrayTable {
                    MyGame.Example.ArrayStruct a;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<MyGame.Example.ArrayTable>]
            struct Exchange { }
        }
    }
}
