// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/arrays_test.fbs
// root_type ArrayTable
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'arrays_test.MyGame.Example.ArrayStruct'/>
        <see cref = 'arrays_test.MyGame.Example.ArrayTable'/>
        <see cref = 'arrays_test.MyGame.Example.LargeArrayStruct'/>
        <see cref = 'arrays_test.MyGame.Example.NestedStruct'/>
    */
    public interface arrays_test {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "ArrayTable";
            public const string file_identifier = "ARRT";
            public const string file_extension = "mon";
        }

        // namespace MyGame
        public struct MyGame {

            // namespace MyGame.Example
            public struct Example {

                /**
                FlatBuffers base type: byte
                */
                public enum TestEnum {
                    A = 0,
                    B = 1,
                    C = 2,
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class NestedStruct {
                    [D(2)] int[] a;
                    MyGame.Example.TestEnum b;
                    [D(2)] MyGame.Example.TestEnum[] c;
                    [D(2)] long[] d;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class ArrayStruct {
                    float a;
                    [D(15)] int[] b;
                    sbyte c;
                    [D(2)] MyGame.Example.NestedStruct[] d;
                    int e;
                    [D(2)] long[] f;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class LargeArrayStruct {
                    [D(64)] byte[] d;
                    [D(64)] float[] e;
                    [D(64)] bool[] f;
                    [D(64)] MyGame.Example.NestedStruct[] g;
                    [D(64)] MyGame.Example.TestEnum[] h;
                }

                public class ArrayTable {
                    MyGame.Example.ArrayStruct a;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<MyGame.Example.ArrayTable>]
            struct Exchange { }
        }
    }
}
