// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: arrow/Schema.fbs, arrow/File.fbs
// root_type Schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Binary'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.BinaryView'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Block'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Bool'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Buffer'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Date'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Decimal'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.DictionaryEncoding'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Duration'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Field'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.FixedSizeBinary'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.FixedSizeList'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.FloatingPoint'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Footer'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Int'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Interval'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.KeyValue'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.LargeBinary'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.LargeList'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.LargeListView'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.LargeUtf8'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.List'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.ListView'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Map'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Null'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.RunEndEncoded'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Schema'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Struct'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Time'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Timestamp'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Type'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Union'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Utf8'/>
        <see cref = 'arrow_File.org.apache.arrow.flatbuf.Utf8View'/>
    */
    public interface arrow_File {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Schema";
        }

        // namespace org
        public struct org {

            // namespace org.apache
            public struct apache {

                // namespace org.apache.arrow
                public struct arrow {

                    // namespace org.apache.arrow.flatbuf
                    public struct flatbuf {

                        /**
                        FlatBuffers base type: short
                        */
                        public enum MetadataVersion {
                            /**
                            0.1.0 (October 2016).
                            */
                            V1 = 0,
                            /**
                            0.2.0 (February 2017). Non-backwards compatible with V1.
                            */
                            V2 = 1,
                            /**
                            0.3.0 -&gt; 0.7.1 (May - December 2017). Non-backwards compatible with V2.
                            */
                            V3 = 2,
                            /**
                            &gt;= 0.8.0 (December 2017). Non-backwards compatible with V3.
                            */
                            V4 = 3,
                            /**
                            &gt;= 1.0.0 (July 2020). Backwards compatible with V4 (V5 readers can read V4
                            metadata and IPC messages). Implementations are recommended to provide a
                            V4 compatibility mode with V5 format changes disabled.
                            Incompatible changes between V4 and V5:
                            - Union buffer layout has changed. In V5, Unions don't have a validity
                            bitmap buffer.
                            */
                            V5 = 4,
                        }

                        /**
                        Represents Arrow Features that might not have full support
                        within implementations. This is intended to be used in
                        two scenarios:
                        1.  A mechanism for readers of Arrow Streams
                        and files to understand that the stream or file makes
                        use of a feature that isn't supported or unknown to
                        the implementation (and therefore can meet the Arrow
                        forward compatibility guarantees).
                        2.  A means of negotiating between a client and server
                        what features a stream is allowed to use. The enums
                        values here are intended to represent higher level
                        features, additional details may be negotiated
                        with key-value pairs specific to the protocol.
                        Enums added to this list should be assigned power-of-two values
                        to facilitate exchanging and comparing bitmaps for supported
                        features.
                        FlatBuffers base type: long
                        */
                        public enum Feature {
                            /**
                            Needed to make flatbuffers happy.
                            */
                            UNUSED = 0,
                            /**
                            The stream makes use of multiple full dictionaries with the
                            same ID and assumes clients implement dictionary replacement
                            correctly.
                            */
                            DICTIONARY_REPLACEMENT = 1,
                            /**
                            The stream makes use of compressed bodies as described
                            in Message.fbs.
                            */
                            COMPRESSED_BODY = 2,
                        }

                        /**
                        These are stored in the flatbuffer in the Type union below
                        */
                        public class Null {
                        }

                        /**
                        A Struct_ in the flatbuffer metadata is the same as an Arrow Struct
                        (according to the physical memory layout). We used Struct_ here as
                        Struct is a reserved word in Flatbuffers
                        */
                        public class Struct {
                        }

                        public class List {
                        }

                        /**
                        Same as List, but with 64-bit offsets, allowing to represent
                        extremely large data values.
                        */
                        public class LargeList {
                        }

                        /**
                        Represents the same logical types that List can, but contains offsets and
                        sizes allowing for writes in any order and sharing of child values among
                        list values.
                        */
                        public class ListView {
                        }

                        /**
                        Same as ListView, but with 64-bit offsets and sizes, allowing to represent
                        extremely large data values.
                        */
                        public class LargeListView {
                        }

                        public class FixedSizeList {
                            /**
                            Number of list items per value
                            */
                            int listSize;
                        }

                        /**
                        A Map is a logical nested type that is represented as
                        List&lt;entries: Struct&lt;key: K, value: V&gt;&gt;
                        In this layout, the keys and values are each respectively contiguous. We do
                        not constrain the key and value types, so the application is responsible
                        for ensuring that the keys are hashable and unique. Whether the keys are sorted
                        may be set in the metadata for this field.
                        In a field with Map type, the field has a child Struct field, which then
                        has two children: the key type and the value type. The names of the
                        child fields may be respectively "entries", "key", and "value", but this is
                        not enforced.
                        Map
                        ```text
                        - child[0] entries: Struct
                        - child[0] key: K
                        - child[1] value: V
                        ```
                        Neither the "entries" field nor the "key" field may be nullable.
                        The metadata is structured so that Arrow systems without special handling
                        for Map can make Map an alias for List. The "layout" attribute for the Map
                        field must have the same contents as a List.
                        */
                        public class Map {
                            /**
                            Set to true if the keys within each value are sorted
                            */
                            bool keysSorted;
                        }

                        /**
                        FlatBuffers base type: short
                        */
                        public enum UnionMode {
                            Sparse = 0,
                            Dense = 1,
                        }

                        /**
                        A union is a complex type with children in Field
                        By default ids in the type vector refer to the offsets in the children
                        optionally typeIds provides an indirection between the child offset and the type id
                        for each child `typeIds[offset]` is the id used in the type vector
                        */
                        public class Union {
                            org.apache.arrow.flatbuf.UnionMode mode;
                            /**
                            optional, describes typeid of each child.
                            */
                            int[,,] typeIds;
                        }

                        public class Int {
                            /**
                            restricted to 8, 16, 32, and 64 in v1
                            */
                            int bitWidth;
                            bool is_signed;
                        }

                        /**
                        FlatBuffers base type: short
                        */
                        public enum Precision {
                            HALF = 0,
                            SINGLE = 1,
                            DOUBLE = 2,
                        }

                        public class FloatingPoint {
                            org.apache.arrow.flatbuf.Precision precision;
                        }

                        /**
                        Unicode with UTF-8 encoding
                        */
                        public class Utf8 {
                        }

                        /**
                        Opaque binary data
                        */
                        public class Binary {
                        }

                        /**
                        Same as Utf8, but with 64-bit offsets, allowing to represent
                        extremely large data values.
                        */
                        public class LargeUtf8 {
                        }

                        /**
                        Same as Binary, but with 64-bit offsets, allowing to represent
                        extremely large data values.
                        */
                        public class LargeBinary {
                        }

                        /**
                        Logically the same as Utf8, but the internal representation uses a view
                        struct that contains the string length and either the string's entire data
                        inline (for small strings) or an inlined prefix, an index of another buffer,
                        and an offset pointing to a slice in that buffer (for non-small strings).
                        Since it uses a variable number of data buffers, each Field with this type
                        must have a corresponding entry in `variadicBufferCounts`.
                        */
                        public class Utf8View {
                        }

                        /**
                        Logically the same as Binary, but the internal representation uses a view
                        struct that contains the string length and either the string's entire data
                        inline (for small strings) or an inlined prefix, an index of another buffer,
                        and an offset pointing to a slice in that buffer (for non-small strings).
                        Since it uses a variable number of data buffers, each Field with this type
                        must have a corresponding entry in `variadicBufferCounts`.
                        */
                        public class BinaryView {
                        }

                        public class FixedSizeBinary {
                            /**
                            Number of bytes per value
                            */
                            int byteWidth;
                        }

                        public class Bool {
                        }

                        /**
                        Contains two child arrays, run_ends and values.
                        The run_ends child array must be a 16/32/64-bit integer array
                        which encodes the indices at which the run with the value in
                        each corresponding index in the values child array ends.
                        Like list/struct types, the value array can be of any type.
                        */
                        public class RunEndEncoded {
                        }

                        /**
                        Exact decimal value represented as an integer value in two's
                        complement. Currently 32-bit (4-byte), 64-bit (8-byte),
                        128-bit (16-byte) and 256-bit (32-byte) integers are used.
                        The representation uses the endianness indicated in the Schema.
                        */
                        public class Decimal {
                            /**
                            Total number of decimal digits
                            */
                            int precision;
                            /**
                            Number of digits after the decimal point "."
                            */
                            int scale;
                            /**
                            Number of bits per value. The accepted widths are 32, 64, 128 and 256.
                            We use bitWidth for consistency with Int::bitWidth.
                            */
                            [Default("128")] int bitWidth;
                        }

                        /**
                        FlatBuffers base type: short
                        */
                        public enum DateUnit {
                            DAY = 0,
                            MILLISECOND = 1,
                        }

                        // Left as an ordinary pack on purpose: this table describes the logical time type of an Arrow column
                        // (its unit, its timezone) and never carries a time value — those live in Arrow's binary buffers,
                        // outside this schema. When you model the values themselves, a date is `class D : DateTimeDef { min; max; precision => TimeSpan.FromDays(1); }`.
                        /**
                        Date is either a 32-bit or 64-bit signed integer type representing an
                        elapsed time since UNIX epoch (1970-01-01), stored in either of two units:
                        * Milliseconds (64 bits) indicating UNIX time elapsed since the epoch (no
                        leap seconds), where the values are evenly divisible by 86400000
                        * Days (32 bits) since the UNIX epoch
                        */
                        public class Date {
                            [Default("MILLISECOND")] org.apache.arrow.flatbuf.DateUnit unit;
                        }

                        /**
                        FlatBuffers base type: short
                        */
                        public enum TimeUnit {
                            SECOND = 0,
                            MILLISECOND = 1,
                            MICROSECOND = 2,
                            NANOSECOND = 3,
                        }

                        // Left as an ordinary pack on purpose: this table describes the logical time type of an Arrow column
                        // (its unit, its timezone) and never carries a time value — those live in Arrow's binary buffers,
                        // outside this schema. When you model the values themselves, a time of day is `class T : TimeSpanDef { interval => TimeSpan.FromDays(1); precision; }`.
                        /**
                        Time is either a 32-bit or 64-bit signed integer type representing an
                        elapsed time since midnight, stored in either of four units: seconds,
                        milliseconds, microseconds or nanoseconds.
                        The integer `bitWidth` depends on the `unit` and must be one of the following:
                        * SECOND and MILLISECOND: 32 bits
                        * MICROSECOND and NANOSECOND: 64 bits
                        The allowed values are between 0 (inclusive) and 86400 (=24*60*60) seconds
                        (exclusive), adjusted for the time unit (for example, up to 86400000
                        exclusive for the MILLISECOND unit).
                        This definition doesn't allow for leap seconds. Time values from
                        measurements with leap seconds will need to be corrected when ingesting
                        into Arrow (for example by replacing the value 86400 with 86399).
                        */
                        public class Time {
                            [Default("MILLISECOND")] org.apache.arrow.flatbuf.TimeUnit unit;
                            [Default("32")] int bitWidth;
                        }

                        // Left as an ordinary pack on purpose: this table describes the logical time type of an Arrow column
                        // (its unit, its timezone) and never carries a time value — those live in Arrow's binary buffers,
                        // outside this schema. When you model the values themselves, a wall-clock instant is `DateTime`, or `class T : DateTimeDef { min; max; precision; }` when the epoch and resolution are pinned.
                        /**
                        Timestamp is a 64-bit signed integer representing an elapsed time since a
                        fixed epoch, stored in either of four units: seconds, milliseconds,
                        microseconds or nanoseconds, and is optionally annotated with a timezone.
                        Timestamp values do not include any leap seconds (in other words, all
                        days are considered 86400 seconds long).
                        Timestamps with a non-empty timezone
                        ------------------------------------
                        If a Timestamp column has a non-empty timezone value, its epoch is
                        1970-01-01 00:00:00 (January 1st 1970, midnight) in the *UTC* timezone
                        (the Unix epoch), regardless of the Timestamp's own timezone.
                        Therefore, timestamp values with a non-empty timezone correspond to
                        physical points in time together with some additional information about
                        how the data was obtained and/or how to display it (the timezone).
                        For example, the timestamp value 0 with the timezone string "Europe/Paris"
                        corresponds to "January 1st 1970, 00h00" in the UTC timezone, but the
                        application may prefer to display it as "January 1st 1970, 01h00" in
                        the Europe/Paris timezone (which is the same physical point in time).
                        One consequence is that timestamp values with a non-empty timezone
                        can be compared and ordered directly, since they all share the same
                        well-known point of reference (the Unix epoch).
                        Timestamps with an unset / empty timezone
                        -----------------------------------------
                        If a Timestamp column has no timezone value, its epoch is
                        1970-01-01 00:00:00 (January 1st 1970, midnight) in an *unknown* timezone.
                        Therefore, timestamp values without a timezone cannot be meaningfully
                        interpreted as physical points in time, but only as calendar / clock
                        indications ("wall clock time") in an unspecified timezone.
                        For example, the timestamp value 0 with an empty timezone string
                        corresponds to "January 1st 1970, 00h00" in an unknown timezone: there
                        is not enough information to interpret it as a well-defined physical
                        point in time.
                        One consequence is that timestamp values without a timezone cannot
                        be reliably compared or ordered, since they may have different points of
                        reference.  In particular, it is *not* possible to interpret an unset
                        or empty timezone as the same as "UTC".
                        Conversion between timezones
                        ----------------------------
                        If a Timestamp column has a non-empty timezone, changing the timezone
                        to a different non-empty value is a metadata-only operation:
                        the timestamp values need not change as their point of reference remains
                        the same (the Unix epoch).
                        However, if a Timestamp column has no timezone value, changing it to a
                        non-empty value requires to think about the desired semantics.
                        One possibility is to assume that the original timestamp values are
                        relative to the epoch of the timezone being set; timestamp values should
                        then adjusted to the Unix epoch (for example, changing the timezone from
                        empty to "Europe/Paris" would require converting the timestamp values
                        from "Europe/Paris" to "UTC", which seems counter-intuitive but is
                        nevertheless correct).
                        Guidelines for encoding data from external libraries
                        ----------------------------------------------------
                        Date &amp; time libraries often have multiple different data types for temporal
                        data. In order to ease interoperability between different implementations the
                        Arrow project has some recommendations for encoding these types into a Timestamp
                        column.
                        An "instant" represents a physical point in time that has no relevant timezone
                        (for example, astronomical data). To encode an instant, use a Timestamp with
                        the timezone string set to "UTC", and make sure the Timestamp values
                        are relative to the UTC epoch (January 1st 1970, midnight).
                        A "zoned date-time" represents a physical point in time annotated with an
                        informative timezone (for example, the timezone in which the data was
                        recorded).  To encode a zoned date-time, use a Timestamp with the timezone
                        string set to the name of the timezone, and make sure the Timestamp values
                        are relative to the UTC epoch (January 1st 1970, midnight).
                        (There is some ambiguity between an instant and a zoned date-time with the
                        UTC timezone.  Both of these are stored the same in Arrow.  Typically,
                        this distinction does not matter.  If it does, then an application should
                        use custom metadata or an extension type to distinguish between the two cases.)
                        An "offset date-time" represents a physical point in time combined with an
                        explicit offset from UTC.  To encode an offset date-time, use a Timestamp
                        with the timezone string set to the numeric timezone offset string
                        (e.g. "+03:00"), and make sure the Timestamp values are relative to
                        the UTC epoch (January 1st 1970, midnight).
                        A "naive date-time" (also called "local date-time" in some libraries)
                        represents a wall clock time combined with a calendar date, but with
                        no indication of how to map this information to a physical point in time.
                        Naive date-times must be handled with care because of this missing
                        information, and also because daylight saving time (DST) may make
                        some values ambiguous or nonexistent. A naive date-time may be
                        stored as a struct with Date and Time fields. However, it may also be
                        encoded into a Timestamp column with an empty timezone. The timestamp
                        values should be computed "as if" the timezone of the date-time values
                        was UTC; for example, the naive date-time "January 1st 1970, 00h00" would
                        be encoded as timestamp value 0.
                        */
                        public class Timestamp {
                            org.apache.arrow.flatbuf.TimeUnit unit;
                            /**
                            The timezone is an optional string indicating the name of a timezone,
                            one of:
                            * As used in the Olson timezone database (the "tz database" or
                            "tzdata"), such as "America/New_York".
                            * An absolute timezone offset of the form "+XX:XX" or "-XX:XX",
                            such as "+07:30".
                            Whether a timezone string is present indicates different semantics about
                            the data (see above).
                            */
                            string timezone;
                        }

                        /**
                        The unit of an Interval.
                        All integers in the units below are stored in the endianness indicated
                        by the schema.
                        FlatBuffers base type: short
                        */
                        public enum IntervalUnit {
                            /**
                            Indicates the number of elapsed whole months, stored as
                            4-byte signed integers.
                            */
                            YEAR_MONTH = 0,
                            /**
                            Indicates the number of elapsed days and milliseconds (no leap seconds),
                            stored as 2 contiguous 32-bit signed integers (8-bytes in total). Support
                            of this IntervalUnit is not required for full Arrow compatibility.
                            */
                            DAY_TIME = 1,
                            /**
                            A triple of the number of elapsed months, days, and nanoseconds.
                            The values are stored contiguously in 16-byte blocks. Months and days are
                            encoded as 32-bit signed integers and nanoseconds is encoded as a 64-bit
                            signed integer. Nanoseconds does not allow for leap seconds. Each field is
                            independent (e.g. there is no constraint that nanoseconds have the same
                            sign as days or that the quantity of nanoseconds represents less than a
                            day's worth of time).
                            */
                            MONTH_DAY_NANO = 2,
                        }

                        // Left as an ordinary pack on purpose: this table describes the logical time type of an Arrow column
                        // (its unit, its timezone) and never carries a time value — those live in Arrow's binary buffers,
                        // outside this schema. When you model the values themselves, a calendar interval has no AdHoc counterpart; keep month / day / nanosecond as separate fields.
                        /**
                        A "calendar" interval which models types that don't necessarily
                        have a precise duration without the context of a base timestamp (e.g.
                        days can differ in length during day light savings time transitions).
                        */
                        public class Interval {
                            org.apache.arrow.flatbuf.IntervalUnit unit;
                        }

                        // Left as an ordinary pack on purpose: this table describes the logical time type of an Arrow column
                        // (its unit, its timezone) and never carries a time value — those live in Arrow's binary buffers,
                        // outside this schema. When you model the values themselves, an elapsed duration is `class D : Duration { max; precision; }`.
                        /**
                        An absolute length of time unrelated to any calendar artifacts.
                        For the purposes of Arrow Implementations, adding this value to a Timestamp
                        ("t1") naively (i.e. simply summing the two numbers) is acceptable even
                        though in some cases the resulting Timestamp (t2) would not account for
                        leap-seconds during the elapsed time between "t1" and "t2".  Similarly,
                        representing the difference between two Unix timestamps is acceptable, but
                        would yield a value that is possibly a few seconds off from the true elapsed
                        time.
                        The resolution defaults to millisecond, but can be any of the other
                        supported TimeUnit values as with Timestamp and Time types.  This type is
                        always represented as an 8-byte integer.
                        */
                        public class Duration {
                            [Default("MILLISECOND")] org.apache.arrow.flatbuf.TimeUnit unit;
                        }

                        /**
                        ----------------------------------------------------------------------
                        Top-level Type value, enabling extensible type-specific metadata. We can
                        add new logical types to Type without breaking backwards compatibility
                        FlatBuffers union: exactly one of the fields below is set.
                        */
                        public class Type {
                            bool Null; // empty table org.apache.arrow.flatbuf.Null: presence flag
                            org.apache.arrow.flatbuf.Int Int;
                            org.apache.arrow.flatbuf.FloatingPoint FloatingPoint;
                            bool Binary; // empty table org.apache.arrow.flatbuf.Binary: presence flag
                            bool Utf8; // empty table org.apache.arrow.flatbuf.Utf8: presence flag
                            bool Bool; // empty table org.apache.arrow.flatbuf.Bool: presence flag
                            org.apache.arrow.flatbuf.Decimal Decimal;
                            org.apache.arrow.flatbuf.Date Date;
                            org.apache.arrow.flatbuf.Time Time;
                            org.apache.arrow.flatbuf.Timestamp Timestamp;
                            org.apache.arrow.flatbuf.Interval Interval;
                            bool List; // empty table org.apache.arrow.flatbuf.List: presence flag
                            bool Struct; // empty table org.apache.arrow.flatbuf.Struct: presence flag
                            org.apache.arrow.flatbuf.Union Union;
                            org.apache.arrow.flatbuf.FixedSizeBinary FixedSizeBinary;
                            org.apache.arrow.flatbuf.FixedSizeList FixedSizeList;
                            org.apache.arrow.flatbuf.Map Map;
                            org.apache.arrow.flatbuf.Duration Duration;
                            bool LargeBinary; // empty table org.apache.arrow.flatbuf.LargeBinary: presence flag
                            bool LargeUtf8; // empty table org.apache.arrow.flatbuf.LargeUtf8: presence flag
                            bool LargeList; // empty table org.apache.arrow.flatbuf.LargeList: presence flag
                            bool RunEndEncoded; // empty table org.apache.arrow.flatbuf.RunEndEncoded: presence flag
                            bool BinaryView; // empty table org.apache.arrow.flatbuf.BinaryView: presence flag
                            bool Utf8View; // empty table org.apache.arrow.flatbuf.Utf8View: presence flag
                            bool ListView; // empty table org.apache.arrow.flatbuf.ListView: presence flag
                            bool LargeListView; // empty table org.apache.arrow.flatbuf.LargeListView: presence flag
                        }

                        /**
                        ----------------------------------------------------------------------
                        user defined key value pairs to add custom metadata to Arrow
                        key namespacing is the responsibility of the user
                        */
                        public class KeyValue {
                            string key;
                            string value;
                        }

                        // FlatBuffers enum (base type short) with fewer than two values: AdHoc rejects such enums, kept as a constants container.
                        /**
                        ----------------------------------------------------------------------
                        Dictionary encoding metadata
                        Maintained for forwards compatibility, in the future
                        Dictionaries might be explicit maps between integers and values
                        allowing for non-contiguous index values
                        */
                        public struct DictionaryKind {
                            public const int DenseArray = 0;
                        }

                        public class DictionaryEncoding {
                            /**
                            The known dictionary id in the application where this data is used. In
                            the file or streaming formats, the dictionary ids are found in the
                            DictionaryBatch messages
                            */
                            long id;
                            /**
                            The dictionary indices are constrained to be non-negative integers. If
                            this field is null, the indices must be signed int32. To maximize
                            cross-language compatibility and performance, implementations are
                            recommended to prefer signed integer types over unsigned integer types
                            and to avoid uint64 indices unless they are required by an application.
                            */
                            org.apache.arrow.flatbuf.Int indexType;
                            /**
                            By default, dictionaries are not ordered, or the order does not have
                            semantic meaning. In some statistical applications, dictionary-encoding
                            is used to represent ordered categorical data, and we provide a way to
                            preserve that metadata here
                            */
                            bool isOrdered;
                            short dictionaryKind; // values: constants container org.apache.arrow.flatbuf.DictionaryKind
                        }

                        /**
                        ----------------------------------------------------------------------
                        A field represents a named column in a record / row batch or child of a
                        nested type.
                        */
                        public class Field {
                            /**
                            Name is not required (e.g., in a List)
                            */
                            string name;
                            /**
                            Whether or not this field can contain nulls. Should be true in general.
                            */
                            bool nullable;
                            /**
                            This is the type of the decoded value if the field is dictionary encoded.
                            */
                            org.apache.arrow.flatbuf.Type Type;
                            /**
                            Present only if the field is dictionary encoded.
                            */
                            org.apache.arrow.flatbuf.DictionaryEncoding dictionary;
                            /**
                            children apply only to nested data types like Struct, List and Union. For
                            primitive types children will have length 0.
                            */
                            org.apache.arrow.flatbuf.Field[,,] children;
                            /**
                            User-defined metadata
                            */
                            org.apache.arrow.flatbuf.KeyValue[,,] custom_metadata;
                        }

                        /**
                        ----------------------------------------------------------------------
                        Endianness of the platform producing the data
                        FlatBuffers base type: short
                        */
                        public enum Endianness {
                            Little = 0,
                            Big = 1,
                        }

                        /**
                        ----------------------------------------------------------------------
                        A Buffer represents a single contiguous memory segment
                        FlatBuffers struct: fixed layout, every field always present.
                        */
                        public class Buffer {
                            /**
                            The relative offset into the shared memory page where the bytes for this
                            buffer starts
                            */
                            long offset;
                            /**
                            The absolute length (in bytes) of the memory buffer. The memory is found
                            from offset (inclusive) to offset + length (non-inclusive). When building
                            messages using the encapsulated IPC message, padding bytes may be written
                            after a buffer, but such padding bytes do not need to be accounted for in
                            the size here.
                            */
                            long length;
                        }

                        /**
                        ----------------------------------------------------------------------
                        A Schema describes the columns in a row batch
                        */
                        public class Schema {
                            /**
                            endianness of the buffer
                            it is Little Endian by default
                            if endianness doesn't match the underlying system then the vectors need to be converted
                            */
                            [Default("Little")] org.apache.arrow.flatbuf.Endianness endianness;
                            org.apache.arrow.flatbuf.Field[,,] fields;
                            /**
                            User-defined metadata
                            */
                            org.apache.arrow.flatbuf.KeyValue[,,] custom_metadata;
                            /**
                            Features used in the stream/file.
                            */
                            org.apache.arrow.flatbuf.Feature[,,] features;
                        }

                        /**
                        ----------------------------------------------------------------------
                        Arrow File metadata
                        */
                        public class Footer {
                            org.apache.arrow.flatbuf.MetadataVersion version;
                            org.apache.arrow.flatbuf.Schema schema;
                            org.apache.arrow.flatbuf.Block[,,] dictionaries;
                            org.apache.arrow.flatbuf.Block[,,] recordBatches;
                            /**
                            User-defined metadata
                            */
                            org.apache.arrow.flatbuf.KeyValue[,,] custom_metadata;
                        }

                        /**
                        FlatBuffers struct: fixed layout, every field always present.
                        */
                        public class Block {
                            /**
                            Index to the start of the RecordBatch (note this is past the Message header)
                            */
                            long offset;
                            /**
                            Length of the metadata
                            */
                            int metaDataLength;
                            /**
                            Length of the data (this is aligned so there can be a gap between this and
                            the metadata).
                            */
                            long bodyLength;
                        }
                    }
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(org.apache.arrow.flatbuf.Null, org.apache.arrow.flatbuf.Struct, org.apache.arrow.flatbuf.List, org.apache.arrow.flatbuf.LargeList, org.apache.arrow.flatbuf.ListView, org.apache.arrow.flatbuf.LargeListView, org.apache.arrow.flatbuf.FixedSizeList, org.apache.arrow.flatbuf.Map, org.apache.arrow.flatbuf.Union, org.apache.arrow.flatbuf.Int, org.apache.arrow.flatbuf.FloatingPoint, org.apache.arrow.flatbuf.Utf8, org.apache.arrow.flatbuf.Binary, org.apache.arrow.flatbuf.LargeUtf8, org.apache.arrow.flatbuf.LargeBinary, org.apache.arrow.flatbuf.Utf8View, org.apache.arrow.flatbuf.BinaryView, org.apache.arrow.flatbuf.FixedSizeBinary, org.apache.arrow.flatbuf.Bool, org.apache.arrow.flatbuf.RunEndEncoded, org.apache.arrow.flatbuf.Decimal, org.apache.arrow.flatbuf.Date, org.apache.arrow.flatbuf.Time, org.apache.arrow.flatbuf.Timestamp, org.apache.arrow.flatbuf.Interval, org.apache.arrow.flatbuf.Duration, org.apache.arrow.flatbuf.KeyValue, org.apache.arrow.flatbuf.DictionaryEncoding, org.apache.arrow.flatbuf.Field, org.apache.arrow.flatbuf.Schema, org.apache.arrow.flatbuf.Footer)>]
            struct Exchange { }
        }

        // ═════════════════════════ FlatBuffers metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field/pack.
        // Declared inside the project interface; the exchange state lists its packs explicitly, so they are not collected.

        /** Default value of a scalar field, as written in the schema (number, enum member, true/false, nan, inf). */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

    }
}
