// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/include_test/sub/include_test2.fbs, flatbuffers/tests/include_test/include_test1.fbs
// No root_type declared
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'include_test1.MyGame.OtherNameSpace.TableB'/>
        <see cref = 'include_test1.MyGame.OtherNameSpace.Unused'/>
        <see cref = 'include_test1.TableA'/>
    */
    public interface include_test1 {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        public class TableA {
            MyGame.OtherNameSpace.TableB b;
        }

        // namespace MyGame
        public struct MyGame {

            // namespace MyGame.OtherNameSpace
            public struct OtherNameSpace {

                // FlatBuffers enum (base type long) with fewer than two values: AdHoc rejects such enums, kept as a constants container.
                public struct FromInclude {
                    public const long IncludeVal = 0;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class Unused {
                    int a;
                }

                public class TableB {
                    TableA a;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(MyGame.OtherNameSpace.TableB, TableA)>]
            struct Exchange { }
        }
    }
}
