// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/samples/monster.fbs
// root_type Monster
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'monster.MyGame.Sample.Equipment'/>
        <see cref = 'monster.MyGame.Sample.Monster'/>
        <see cref = 'monster.MyGame.Sample.Vec3'/>
        <see cref = 'monster.MyGame.Sample.Weapon'/>
    */
    public interface monster {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Monster";
        }

        // namespace MyGame
        public struct MyGame {

            // namespace MyGame.Sample
            public struct Sample {

                /**
                FlatBuffers base type: byte
                */
                public enum Color {
                    Red = 0,
                    Green = 1,
                    Blue = 2,
                }

                /**
                FlatBuffers union: exactly one of the fields below is set.
                */
                public class Equipment {
                    MyGame.Sample.Weapon Weapon;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class Vec3 {
                    float x;
                    float y;
                    float z;
                }

                public class Monster {
                    MyGame.Sample.Vec3 pos;
                    [Default("150")] short mana;
                    [Default("100")] short hp;
                    string name;
                    /**
                    ⚠ DEPRECATED
                    */
                    [Default("false"), Deprecated] bool friendly;
                    Binary[,,] inventory;
                    [Default("Blue")] MyGame.Sample.Color color;
                    MyGame.Sample.Weapon[,,] weapons;
                    MyGame.Sample.Equipment equipped;
                    MyGame.Sample.Vec3[,,] path;
                }

                public class Weapon {
                    string name;
                    short damage;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(MyGame.Sample.Monster, MyGame.Sample.Weapon)>]
            struct Exchange { }
        }

        // ═════════════════════════ FlatBuffers metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field/pack.
        // Declared inside the project interface; the exchange state lists its packs explicitly, so they are not collected.

        /** Default value of a scalar field, as written in the schema (number, enum member, true/false, nan, inf). */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The field is deprecated in the FlatBuffers schema and must not be written. */
        public class DeprecatedAttribute : Attribute { }

    }
}
