// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/include_test/sub/include_test2.fbs, flatbuffers/tests/include_test/include_test1.fbs, flatbuffers/tests/monster_test.fbs
// root_type Monster
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'monster_test.MyGame.Example.Ability'/>
        <see cref = 'monster_test.MyGame.Example.Any'/>
        <see cref = 'monster_test.MyGame.Example.AnyAmbiguousAliases'/>
        <see cref = 'monster_test.MyGame.Example.AnyUniqueAliases'/>
        <see cref = 'monster_test.MyGame.Example.Monster'/>
        <see cref = 'monster_test.MyGame.Example.Referrable'/>
        <see cref = 'monster_test.MyGame.Example.Stat'/>
        <see cref = 'monster_test.MyGame.Example.StructOfStructs'/>
        <see cref = 'monster_test.MyGame.Example.StructOfStructsOfStructs'/>
        <see cref = 'monster_test.MyGame.Example.Test'/>
        <see cref = 'monster_test.MyGame.Example.TestSimpleTableWithEnum'/>
        <see cref = 'monster_test.MyGame.Example.TypeAliases'/>
        <see cref = 'monster_test.MyGame.Example.Vec3'/>
        <see cref = 'monster_test.MyGame.Example2.Monster'/>
        <see cref = 'monster_test.MyGame.InParentNamespace'/>
        <see cref = 'monster_test.MyGame.OtherNameSpace.TableB'/>
        <see cref = 'monster_test.MyGame.OtherNameSpace.Unused'/>
        <see cref = 'monster_test.TableA'/>
    */
    public interface monster_test {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Monster";
            public const string file_identifier = "MONS";
            public const string file_extension = "mon";
        }

        public class TableA {
            MyGame.OtherNameSpace.TableB b;
        }

        // namespace MyGame
        public struct MyGame {

            public class InParentNamespace {
            }

            // namespace MyGame.OtherNameSpace
            public struct OtherNameSpace {

                // FlatBuffers enum (base type long) with fewer than two values: AdHoc rejects such enums, kept as a constants container.
                public struct FromInclude {
                    public const long IncludeVal = 0;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class Unused {
                    int a;
                }

                public class TableB {
                    TableA a;
                }
            }

            // namespace MyGame.Example2
            public struct Example2 {

                public class Monster {
                }
            }

            // namespace MyGame.Example
            public struct Example {

                /**
                Composite components of Monster color.
                FlatBuffers base type: ubyte (bit_flags)
                */
                [Flags]
                public enum Color {
                    /**
                    color Red = (1u &lt;&lt; 0)
                    */
                    Red = 1,
                    /**
                    \brief color Green
                    Green is bit_flag with value (1u &lt;&lt; 1)
                    */
                    Green = 2,
                    /**
                    \brief color Blue (1u &lt;&lt; 3)
                    */
                    Blue = 8,
                }

                /**
                FlatBuffers base type: byte
                */
                public enum Race {
                    None = -1,
                    Human = 0,
                    Dwarf = 1,
                    Elf = 2,
                }

                /**
                FlatBuffers base type: ulong (bit_flags)
                */
                [Flags]
                public enum LongEnum : long {
                    LongOne = 2,
                    LongTwo = 4,
                    /**
                    Because this is a bitflag, 40 will be out of range of a 32-bit integer,
                    allowing us to exercise any logic special to big numbers.
                    */
                    LongBig = 1099511627776,
                }

                /**
                FlatBuffers union: exactly one of the fields below is set.
                */
                public class Any {
                    MyGame.Example.Monster Monster;
                    MyGame.Example.TestSimpleTableWithEnum TestSimpleTableWithEnum;
                    bool Monster2; // empty table MyGame.Example2.Monster: presence flag
                }

                /**
                FlatBuffers union: exactly one of the fields below is set.
                */
                public class AnyUniqueAliases {
                    MyGame.Example.Monster M;
                    MyGame.Example.TestSimpleTableWithEnum TS;
                    bool M2; // empty table MyGame.Example2.Monster: presence flag
                }

                /**
                FlatBuffers union: exactly one of the fields below is set.
                */
                public class AnyAmbiguousAliases {
                    MyGame.Example.Monster M1;
                    MyGame.Example.Monster M2;
                    MyGame.Example.Monster M3;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class Test {
                    short a;
                    sbyte b;
                }

                /**
                (csharp_partial)
                (private)
                */
                public class TestSimpleTableWithEnum {
                    [Default("Green")] MyGame.Example.Color color;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                (force_align: 8)
                */
                [ForceAlign(8)]
                public class Vec3 {
                    float x;
                    float y;
                    float z;
                    double test1;
                    MyGame.Example.Color test2;
                    MyGame.Example.Test test3;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class Ability {
                    [SortKey] uint id;
                    uint distance;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class StructOfStructs {
                    MyGame.Example.Ability a;
                    MyGame.Example.Test b;
                    MyGame.Example.Ability c;
                }

                /**
                FlatBuffers struct: fixed layout, every field always present.
                */
                public class StructOfStructsOfStructs {
                    MyGame.Example.StructOfStructs a;
                }

                public class Stat {
                    string id;
                    long val;
                    [SortKey] ushort count;
                }

                public class Referrable {
                    [SortKey, User("hash", "fnv1a_64")] ulong id;
                }

                /**
                an example documentation comment: "monster object"
                */
                public class Monster {
                    [FieldId(0)] MyGame.Example.Vec3 pos;
                    [Default("100"), FieldId(2)] short hp;
                    [Default("150"), FieldId(1)] short mana;
                    [FieldId(3), SortKey] string name;
                    [Default("Blue"), FieldId(6)] MyGame.Example.Color color;
                    [FieldId(5)] Binary[,,] inventory;
                    /**
                    ⚠ DEPRECATED
                    */
                    [Default("false"), Deprecated, User("priority", "1"), FieldId(4)] bool friendly;
                    /**
                    an example documentation comment: this will end up in the generated code
                    multiline too
                    */
                    [FieldId(11)] MyGame.Example.Monster[,,] testarrayoftables;
                    [FieldId(10)] string[,,] testarrayofstring;
                    [FieldId(28)] string[,,] testarrayofstring2;
                    [FieldId(24)] bool[,,] testarrayofbools;
                    [FieldId(29)] MyGame.Example.Ability[,,] testarrayofsortedstruct;
                    /**
                    Test referring by full namespace.
                    */
                    [FieldId(12)] MyGame.Example.Monster enemy;
                    [FieldId(8)] MyGame.Example.Any test;
                    [FieldId(9)] MyGame.Example.Test[,,] test4;
                    [FieldId(31)] MyGame.Example.Test[,,] test5;
                    /**
                    DROPPED: an embedded FlatBuffer of type `Monster`, kept as opaque bytes. In AdHoc it would simply be that pack
                    as this field's type.
                    */
                    [FieldId(13), User("nested_flatbuffer", "Monster")] Binary[,,] testnestedflatbuffer;
                    [FieldId(14)] MyGame.Example.Stat testempty;
                    [FieldId(15)] bool testbool;
                    [FieldId(16), User("hash", "fnv1_32")] int testhashs32_fnv1;
                    [FieldId(17), User("hash", "fnv1_32")] uint testhashu32_fnv1;
                    [FieldId(18), User("hash", "fnv1_64")] long testhashs64_fnv1;
                    [FieldId(19), User("hash", "fnv1_64")] ulong testhashu64_fnv1;
                    [FieldId(20), User("hash", "fnv1a_32")] int testhashs32_fnv1a;
                    [FieldId(21), User("hash", "fnv1a_32"), User("cpp_type", "Stat")] uint testhashu32_fnv1a;
                    [FieldId(22), User("hash", "fnv1a_64")] long testhashs64_fnv1a;
                    [FieldId(23), User("hash", "fnv1a_64")] ulong testhashu64_fnv1a;
                    [Default("3.14159"), FieldId(25)] float testf;
                    [Default("3"), FieldId(26)] float testf2;
                    [FieldId(27)] float testf3;
                    /**
                    DROPPED: a self-describing FlexBuffer, kept as opaque bytes. AdHoc has no untyped value; give it a pack or a
                    Stream.
                    */
                    [FieldId(30), User("flexbuffer", "")] Binary[,,] flex;
                    [FieldId(32)] long[,,] vector_of_longs;
                    [FieldId(33)] double[,,] vector_of_doubles;
                    [FieldId(34)] bool parent_namespace_test; // empty table MyGame.InParentNamespace: presence flag
                    [FieldId(35)] MyGame.Example.Referrable[,,] vector_of_referrables;
                    [FieldId(36), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT")] ulong single_weak_reference;
                    [FieldId(37), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT")] ulong[,,] vector_of_weak_references;
                    /**
                    was shared_ptr
                    */
                    [FieldId(38), User("cpp_ptr_type", "default_ptr_type")] MyGame.Example.Referrable[,,] vector_of_strong_referrables;
                    /**
                    was shared_ptr as well
                    */
                    [FieldId(39), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT"), User("cpp_ptr_type", "naked")] ulong co_owning_reference;
                    /**
                    was shared_ptr
                    */
                    [FieldId(40), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT"), User("cpp_ptr_type", "default_ptr_type"), User("cpp_ptr_type_get", ".get()")] ulong[,,] vector_of_co_owning_references;
                    /**
                    was weak_ptr
                    */
                    [FieldId(41), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT"), User("cpp_ptr_type", "naked"), User("cpp_ptr_type_get", "")] ulong non_owning_reference;
                    /**
                    was weak_ptr
                    */
                    [FieldId(42), User("hash", "fnv1a_64"), User("cpp_type", "ReferrableT"), User("cpp_ptr_type", "naked"), User("cpp_ptr_type_get", "")] ulong[,,] vector_of_non_owning_references;
                    [FieldId(44)] MyGame.Example.AnyUniqueAliases any_unique;
                    [FieldId(46)] MyGame.Example.AnyAmbiguousAliases any_ambiguous;
                    [FieldId(47)] MyGame.Example.Color[,,] vector_of_enums;
                    [Default("None"), FieldId(48)] MyGame.Example.Race signed_enum;
                    /**
                    DROPPED: an embedded FlatBuffer of type `Monster`, kept as opaque bytes. In AdHoc it would simply be that pack
                    as this field's type.
                    */
                    [FieldId(49), User("nested_flatbuffer", "Monster")] Binary[,,] testrequirednestedflatbuffer;
                    [FieldId(50)] MyGame.Example.Stat[,,] scalar_key_sorted_tables;
                    [FieldId(51), User("native_inline", "")] MyGame.Example.Test native_inline;
                    /**
                    The default value of this enum will be a numeric zero, which isn't a valid
                    enum value.
                    */
                    [FieldId(52)] MyGame.Example.LongEnum long_enum_non_enum_default;
                    [Default("LongOne"), FieldId(53)] MyGame.Example.LongEnum long_enum_normal_default;
                    /**
                    Test that default values nan and +/-inf work.
                    */
                    [Default("nan"), FieldId(54)] float nan_default;
                    [Default("inf"), FieldId(55)] float inf_default;
                    [Default("+inf"), FieldId(56)] float positive_inf_default;
                    [Default("infinity"), FieldId(57)] float infinity_default;
                    [Default("+infinity"), FieldId(58)] float positive_infinity_default;
                    [Default("-inf"), FieldId(59)] float negative_inf_default;
                    [Default("-infinity"), FieldId(60)] float negative_infinity_default;
                    [Default("inf"), FieldId(61)] double double_inf_default;
                }

                public class TypeAliases {
                    sbyte i8;
                    byte u8;
                    short i16;
                    ushort u16;
                    int i32;
                    uint u32;
                    long i64;
                    ulong u64;
                    float f32;
                    double f64;
                    sbyte[,,] v8;
                    double[,,] vf64;
                }
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // rpc_service methods: Client calls, Server answers (streaming modes are noted in the docs).
            /**
            rpc_service MonsterStorage, streaming: none
            */
            (L____________, MyGame.Example.Stat) Store(MyGame.Example.Monster req);
            /**
            rpc_service MonsterStorage, streaming: server, idempotent
            */
            (L____________, MyGame.Example.Monster) Retrieve(MyGame.Example.Stat req);
            /**
            rpc_service MonsterStorage, streaming: client
            */
            (L____________, MyGame.Example.Stat) GetMaxHitPoint(MyGame.Example.Monster req);
            /**
            rpc_service MonsterStorage, streaming: bidi
            */
            (L____________, MyGame.Example.Stat) GetMinMaxHitPoints(MyGame.Example.Monster req);

            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(MyGame.OtherNameSpace.TableB, TableA, MyGame.InParentNamespace, MyGame.Example2.Monster, MyGame.Example.TestSimpleTableWithEnum, MyGame.Example.Referrable, MyGame.Example.TypeAliases)>]
            struct Exchange { }
        }

        // ═════════════════════════ FlatBuffers metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field/pack.
        // Declared inside the project interface; the exchange state lists its packs explicitly, so they are not collected.

        /** Default value of a scalar field, as written in the schema (number, enum member, true/false, nan, inf). */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** Explicit vtable slot (id: N) of the field in the FlatBuffers table. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(long id) { } }

        /** The field is deprecated in the FlatBuffers schema and must not be written. */
        public class DeprecatedAttribute : Attribute { }

        /** The field is the (key) used to sort vectors of this table/struct. */
        public class SortKeyAttribute : Attribute { }

        /** force_align: N alignment requested in the FlatBuffers schema. */
        public class ForceAlignAttribute : Attribute { public ForceAlignAttribute(long alignment) { } }

        /** Any other FlatBuffers field attribute (hash, nested_flatbuffer, flexbuffer, cpp_type, user-declared ...) as name/value. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class UserAttribute : Attribute { public UserAttribute(string name, string value) { } }

    }
}
