// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/optional_scalars.fbs
// root_type ScalarStuff
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'optional_scalars.optional_scalars2.ScalarStuff'/>
    */
    public interface optional_scalars {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below. Not because FlatBuffers stores scalars raw - AdHoc
        // lays out its own frame and may varint-encode anything - but because a .fbs carries no claim about
        // WHERE a field's values sit: it has no sint32-versus-fixed32 choice, no declared range, no units. The
        // physics of each number is therefore yours to state, and it is the single highest-value edit to make
        // to this file. Fields whose name or documentation does hint at an answer carry a `// physics:` line
        // naming the candidate and the reason; the choice is deliberately left open.
        //   [A(min)] floor, rare excursions up     [V(max)] hugs a ceiling
        //   [X(amplitude)] two-sided around zero   [MinMax(a, b)] hard range, bit-packed, no varint
        // Check the arithmetic first: varint pays while the typical distance from the base stays under about
        // two million, and always loses past 268 435 455 - so timestamps, scaled coordinates, monotonic ids
        // and hashes are losses at a zero base. A span under one byte is rejected; use [MinMax] there.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "ScalarStuff";
            public const string file_identifier = "NULL";
            public const string file_extension = "mon";
        }

        // namespace optional_scalars
        public struct optional_scalars2 {

            /**
            FlatBuffers base type: byte
            */
            public enum OptionalByte {
                None = 0,
                One = 1,
                Two = 2,
            }

            /**
            This table tests optional scalars in tables. It should be integrated with
            the main monster test once most languages support optional scalars.
            */
            public class ScalarStuff {
                sbyte just_i8;
                sbyte? maybe_i8;
                [Default("42")] sbyte default_i8;
                byte just_u8;
                byte? maybe_u8;
                [Default("42")] byte default_u8;
                short just_i16;
                short? maybe_i16;
                [Default("42")] short default_i16;
                ushort just_u16;
                ushort? maybe_u16;
                [Default("42")] ushort default_u16;
                int just_i32;
                int? maybe_i32;
                [Default("42")] int default_i32;
                uint just_u32;
                uint? maybe_u32;
                [Default("42")] uint default_u32;
                long just_i64;
                long? maybe_i64;
                [Default("42")] long default_i64;
                ulong just_u64;
                ulong? maybe_u64;
                [Default("42")] ulong default_u64;
                float just_f32;
                float? maybe_f32;
                [Default("42")] float default_f32;
                double just_f64;
                double? maybe_f64;
                [Default("42")] double default_f64;
                bool just_bool;
                bool? maybe_bool;
                [Default("true")] bool default_bool;
                optional_scalars2.OptionalByte just_enum;
                optional_scalars2.OptionalByte? maybe_enum;
                [Default("One")] optional_scalars2.OptionalByte default_enum;
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<optional_scalars2.ScalarStuff>]
            struct Exchange { }
        }

        // ═════════════════════════ FlatBuffers metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field/pack.
        // Declared inside the project interface; the exchange state lists its packs explicitly, so they are not collected.

        /** Default value of a scalar field, as written in the schema (number, enum member, true/false, nan, inf). */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

    }
}
