// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/reflection/reflection.fbs
// root_type Schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'reflection.reflection2.Enum'/>
        <see cref = 'reflection.reflection2.EnumVal'/>
        <see cref = 'reflection.reflection2.Field'/>
        <see cref = 'reflection.reflection2.KeyValue'/>
        <see cref = 'reflection.reflection2.Object'/>
        <see cref = 'reflection.reflection2.RPCCall'/>
        <see cref = 'reflection.reflection2.Schema'/>
        <see cref = 'reflection.reflection2.SchemaFile'/>
        <see cref = 'reflection.reflection2.Service'/>
        <see cref = 'reflection.reflection2.Type'/>
    */
    public interface reflection {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below. Not because FlatBuffers stores scalars raw - AdHoc
        // lays out its own frame and may varint-encode anything - but because a .fbs carries no claim about
        // WHERE a field's values sit: it has no sint32-versus-fixed32 choice, no declared range, no units. The
        // physics of each number is therefore yours to state, and it is the single highest-value edit to make
        // to this file. Fields whose name or documentation does hint at an answer carry a `// physics:` line
        // naming the candidate and the reason; the choice is deliberately left open.
        //   [A(min)] floor, rare excursions up     [V(max)] hugs a ceiling
        //   [X(amplitude)] two-sided around zero   [MinMax(a, b)] hard range, bit-packed, no varint
        // Check the arithmetic first: varint pays while the typical distance from the base stays under about
        // two million, and always loses past 268 435 455 - so timestamps, scaled coordinates, monotonic ids
        // and hashes are losses at a zero base. A span under one byte is rejected; use [MinMax] there.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Schema";
            public const string file_identifier = "BFBS";
            public const string file_extension = "bfbs";
        }

        // namespace reflection
        public struct reflection2 {

            /**
            These must correspond to the enum in idl.h.
            FlatBuffers base type: byte
            */
            public enum BaseType {
                None = 0,
                UType = 1,
                Bool = 2,
                Byte = 3,
                UByte = 4,
                Short = 5,
                UShort = 6,
                Int = 7,
                UInt = 8,
                Long = 9,
                ULong = 10,
                Float = 11,
                Double = 12,
                String = 13,
                Vector = 14,
                /**
                Used for tables &amp; structs.
                */
                Obj = 15,
                Union = 16,
                Array = 17,
                Vector64 = 18,
                /**
                Add any new type above this value.
                */
                MaxBaseType = 19,
            }

            public class Type {
                reflection2.BaseType base_type;
                /**
                Only if base_type == Vector
                */
                [Default("None")] reflection2.BaseType element;
                /**
                or base_type == Array.
                If base_type == Object, index into "objects" below.
                */
                // physics: an index or a small ordinal, floor at 0 -> consider [A], or [MinMax(a, b)] if you know a hard ceiling
                [Default("-1")] int index;
                /**
                If base_type == Union, UnionType, or integral derived
                from an enum, index into "enums" below.
                If base_type == Vector &amp;&amp; element == Union or UnionType.
                Only if base_type == Array.
                */
                // physics: an element count, floor at 0, unbounded above -> consider [A]
                [Default("0")] ushort fixed_length;
                /**
                The size (octets) of the `base_type` field.
                4 Is a common size due to offsets being that size.
                */
                // physics: an element count, floor at 0, unbounded above -> consider [A]
                [Default("4")] uint base_size;
                /**
                The size (octets) of the `element` field, if present.
                */
                // physics: an element count, floor at 0, unbounded above -> consider [A]
                [Default("0")] uint element_size;
            }

            public class KeyValue {
                [Required, SortKey] string key;
                string value;
            }

            public class EnumVal {
                [Required] string name;
                [SortKey] long value;
                /**
                ⚠ DEPRECATED
                */
                [Deprecated] reflection2.Object Object;
                reflection2.Type union_type;
                string[,,] documentation;
                reflection2.KeyValue[,,] attributes;
            }

            public class Enum {
                [Required, SortKey] string name;
                /**
                In order of their values.
                */
                [Required] reflection2.EnumVal[,,] values;
                [Default("false")] bool is_union;
                [Required] reflection2.Type underlying_type;
                reflection2.KeyValue[,,] attributes;
                string[,,] documentation;
                /**
                File that this Enum is declared in.
                */
                string declaration_file;
            }

            public class Field {
                [Required, SortKey] string name;
                [Required] reflection2.Type Type;
                ushort id;
                /**
                Offset into the vtable for tables, or into the struct.
                */
                // physics: a byte offset, floor at 0 but often huge -> [A] pays only while offsets stay under ~2 million (README section Number encoding)
                ushort offset;
                [Default("0")] long default_integer;
                [Default("0.0")] double default_real;
                [Default("false")] bool deprecated;
                [Default("false")] bool required;
                [Default("false")] bool key;
                reflection2.KeyValue[,,] attributes;
                string[,,] documentation;
                [Default("false")] bool optional;
                /**
                Number of padding octets to always add after this field. Structs only.
                */
                [Default("0")] ushort padding;
                /**
                If the field uses 64-bit offsets.
                */
                [Default("false")] bool offset64;
            }

            public class Object {
                [Required, SortKey] string name;
                /**
                Sorted.
                */
                [Required] reflection2.Field[,,] fields;
                [Default("false")] bool is_struct;
                int minalign;
                /**
                For structs.
                */
                // physics: an element count, floor at 0, unbounded above -> consider [A]
                int bytesize;
                reflection2.KeyValue[,,] attributes;
                string[,,] documentation;
                /**
                File that this Object is declared in.
                */
                string declaration_file;
            }

            public class RPCCall {
                [Required, SortKey] string name;
                /**
                must be a table (not a struct)
                */
                [Required] reflection2.Object request;
                /**
                must be a table (not a struct)
                */
                [Required] reflection2.Object response;
                reflection2.KeyValue[,,] attributes;
                string[,,] documentation;
            }

            public class Service {
                [Required, SortKey] string name;
                reflection2.RPCCall[,,] calls;
                reflection2.KeyValue[,,] attributes;
                string[,,] documentation;
                /**
                File that this Service is declared in.
                */
                string declaration_file;
            }

            /**
            New schema language features that are not supported by old code generators.
            FlatBuffers base type: ulong (bit_flags)
            */
            [Flags]
            public enum AdvancedFeatures {
                AdvancedArrayFeatures = 1,
                AdvancedUnionFeatures = 2,
                OptionalScalars = 4,
                DefaultVectorsAndStrings = 8,
            }

            /**
            File specific information.
            Symbols declared within a file may be recovered by iterating over all
            symbols and examining the `declaration_file` field.
            */
            public class SchemaFile {
                /**
                Filename, relative to project root.
                */
                [Required, SortKey] string filename;
                /**
                Names of included files, relative to project root.
                */
                string[,,] included_filenames;
            }

            public class Schema {
                /**
                Sorted.
                */
                [Required] reflection2.Object[,,] objects;
                /**
                Sorted.
                */
                [Required] reflection2.Enum[,,] enums;
                string file_ident;
                string file_ext;
                reflection2.Object root_table;
                /**
                Sorted.
                */
                reflection2.Service[,,] services;
                reflection2.AdvancedFeatures advanced_features;
                /**
                All the files used in this compilation. Files are relative to where
                flatc was invoked.
                Sorted.
                */
                reflection2.SchemaFile[,,] fbs_files;
            }
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(reflection2.Type, reflection2.KeyValue, reflection2.EnumVal, reflection2.Enum, reflection2.Field, reflection2.Object, reflection2.RPCCall, reflection2.Service, reflection2.SchemaFile, reflection2.Schema)>]
            struct Exchange { }
        }

        // ═════════════════════════ FlatBuffers metadata attributes ═════════════════════════

        // AdHoc custom attributes: carried into the generated code as constants attached to the field/pack.
        // Declared inside the project interface; the exchange state lists its packs explicitly, so they are not collected.

        /** Default value of a scalar field, as written in the schema (number, enum member, true/false, nan, inf). */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The field is deprecated in the FlatBuffers schema and must not be written. */
        public class DeprecatedAttribute : Attribute { }

        /** The (non-scalar) field is required in the FlatBuffers schema. */
        public class RequiredAttribute : Attribute { }

        /** The field is the (key) used to sort vectors of this table/struct. */
        public class SortKeyAttribute : Attribute { }

    }
}
