// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/union_vector/union_vector.fbs
// root_type Movie
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'union_vector.Attacker'/>
        <see cref = 'union_vector.BookReader'/>
        <see cref = 'union_vector.Character'/>
        <see cref = 'union_vector.FallingTub'/>
        <see cref = 'union_vector.Gadget'/>
        <see cref = 'union_vector.HandFan'/>
        <see cref = 'union_vector.Movie'/>
        <see cref = 'union_vector.Rapunzel'/>
    */
    public interface union_vector {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below, and that is a finding about FlatBuffers rather
        // than a gap in this converter. FlatBuffers stores every scalar fixed-width and unencoded, so a .fbs
        // schema never states - and its encoding never implies - where a number's values sit. Declaring a
        // distribution the source does not know would make the wire larger, not smaller.
        // Add one by hand wherever you do know the field: [A(min)] for a counter that hugs its floor,
        // [V(max)] for a remaining budget, [X(amplitude)] for a two-sided delta, [MinMax(a, b)] for a hard
        // range that should bit-pack. A [Default("100")] below is a hint about the common value, not a
        // bound, but it is often the clue that tells you which attribute fits.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Movie";
            public const string file_identifier = "MOVI";
        }

        public class Attacker {
            int sword_attack_damage;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class Rapunzel {
            int hair_length;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class BookReader {
            int books_read;
        }

        /**
        FlatBuffers union: exactly one of the fields below is set.
        */
        public class Character {
            /**
            Can have name be different from type.
            */
            Attacker MuLan;
            /**
            Or just both the same, as before.
            */
            Rapunzel Rapunzel;
            BookReader Belle;
            BookReader BookFan;
            string Other;
            string Unused;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class FallingTub {
            int weight;
        }

        public class HandFan {
            int length;
        }

        /**
        FlatBuffers union: exactly one of the fields below is set.
        */
        public class Gadget {
            FallingTub FallingTub;
            HandFan HandFan;
        }

        public class Movie {
            Character main_character;
            Character[,,] characters;
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(Attacker, HandFan, Movie)>]
            struct Exchange { }
        }
    }
}
