// Generated by FlatBuffers2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: flatbuffers/tests/union_vector/union_vector.fbs
// root_type Movie
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.flatbuffers {
    /**
        <see cref = 'union_vector.Attacker'/>
        <see cref = 'union_vector.BookReader'/>
        <see cref = 'union_vector.Character'/>
        <see cref = 'union_vector.FallingTub'/>
        <see cref = 'union_vector.Gadget'/>
        <see cref = 'union_vector.HandFan'/>
        <see cref = 'union_vector.Movie'/>
        <see cref = 'union_vector.Rapunzel'/>
    */
    public interface union_vector {

        // FlatBuffers states no length bound for vectors or strings, so AdHoc's 255 default would be a
        // truncation and any [D(N)] here would be an invention. Raise the project-wide ceiling instead, and
        // let [D(N)] appear only where the schema really says a size: the fixed arrays `[T:N]` of structs.
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // No [A] / [V] / [X] varint attribute appears below. Not because FlatBuffers stores scalars raw - AdHoc
        // lays out its own frame and may varint-encode anything - but because a .fbs carries no claim about
        // WHERE a field's values sit: it has no sint32-versus-fixed32 choice, no declared range, no units. The
        // physics of each number is therefore yours to state, and it is the single highest-value edit to make
        // to this file. Fields whose name or documentation does hint at an answer carry a `// physics:` line
        // naming the candidate and the reason; the choice is deliberately left open.
        //   [A(min)] floor, rare excursions up     [V(max)] hugs a ceiling
        //   [X(amplitude)] two-sided around zero   [MinMax(a, b)] hard range, bit-packed, no varint
        // Check the arithmetic first: varint pays while the typical distance from the base stays under about
        // two million, and always loses past 268 435 455 - so timestamps, scaled coordinates, monotonic ids
        // and hashes are losses at a zero base. A span under one byte is rejected; use [MinMax] there.

        /** root_type / file_identifier / file_extension of the schema (non-transmittable constants). */
        public struct FlatBufferFile {
            public const string root_type = "Movie";
            public const string file_identifier = "MOVI";
        }

        public class Attacker {
            int sword_attack_damage;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class Rapunzel {
            // physics: an element count, floor at 0, unbounded above -> consider [A]
            int hair_length;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class BookReader {
            int books_read;
        }

        /**
        FlatBuffers union: exactly one of the fields below is set.
        */
        public class Character {
            /**
            Can have name be different from type.
            */
            Attacker MuLan;
            /**
            Or just both the same, as before.
            */
            Rapunzel Rapunzel;
            BookReader Belle;
            BookReader BookFan;
            string Other;
            string Unused;
        }

        /**
        FlatBuffers struct: fixed layout, every field always present.
        */
        public class FallingTub {
            int weight;
        }

        public class HandFan {
            // physics: an element count, floor at 0, unbounded above -> consider [A]
            int length;
        }

        /**
        FlatBuffers union: exactly one of the fields below is set.
        */
        public class Gadget {
            FallingTub FallingTub;
            HandFan HandFan;
        }

        public class Movie {
            Character main_character;
            Character[,,] characters;
        }

        // ═════════════════════════ demo topology ═════════════════════════

        // The side that owns the root object and calls the rpc_service methods.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Connection : Connects<Client, Server> {
            // Every table not owned by an rpc method, in both directions; the FSM never transitions.
            [_____lr_____<(Attacker, HandFan, Movie)>]
            struct Exchange { }
        }
    }
}
